apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-secret
  namespace: kargo-demo-1
stringData:
  apiKey: <api-token>
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-cluster-secret
  namespace: "kargo-cluster-secrets"
stringData:
  apiKey: <api-token>